### ISSUE TITLE
IAttaccante.java non riconosciuto come Java file da IntelliJ

### ISSUE THREAD

**Issue by Fs00** [Fs00/rpg-game-4inc#1]
Quando creo il file IAttaccante.java, IntelliJ mi dà errore nel parsing del template (cosa non vera, perché il file viene creato con il template giusto) e quindi l'IDE si rifiuta di riconoscerlo come file Java. La cosa assurda è che cambiando nome al file tutto funziona perfettamente!
Ho provato a ricreare il progetto e cancellare la cache dell'IDE ma niente. Capita anche a voi questo problema?

**Comment by alegotta** [comment]
No, a me il file viene riconosciuto correttamente. Potresti mandare uno screenshot? Sei su Linux o su Windows?

**Comment by Fs00** [comment]
Risolto. Leggendo meglio il messaggio di errore, ho scoperto che il presunto errore di parsing del template causava la modifica delle impostazioni di riconoscimento dei tipi di file per nome; "IAttaccante.java" diventava quindi infatti un pattern di riconoscimento dei file di testo normali.
