### ISSUE TITLE
Come va implementata la ritirata?

### ISSUE THREAD

**Issue by Fs00** [Fs00/rpg-game-4inc#12]
@AlibabaSakura suggerisce di rivedere l'implementazione della ritirata attualmente presente (che verifica solo se la velocità di chi tenta la ritirata è maggiore di quella del nemico), in modo che sia sempre basata sulla velocità ma che dia a entrambi la possibilità di ritirarsi, non solo al personaggio più veloce.
A questo punto ho pensato che sarebbe interessante fare in modo che la probabilità sia basata sulla differenza di velocità tra i due personaggi, magari qualcosa come *(50 + (VEL personaggio che si vuole ritirare **-** VEL nemico))%*, in modo da avere una probabilità base del 50% che viene aumentata se la propria velocità è maggiore di quella del nemico, altrimenti diminuita (dato che la differenza tra le due velocità sarebbe negativa).
Cosa ne pensate?

**Comment by alegotta** [comment]
Buona idea. Se volete posso implementarla io

**Comment by Fs00** [comment]
Allora ok, ci pensi tu @alegotta. @AlibabaSakura sei d'accordo anche con la percentuale base del 50%?

**Comment by AlibabaSakura** [comment]
Il rate ci può stare. Vada per la tua formula

**Comment by Fs00** [comment]
Chiudo, dato che l'implementazione è stata completata.
