### ISSUE TITLE
Ribilanciamento meccaniche e ritocchi

### ISSUE THREAD

**Issue by Fs00** [Fs00/rpg-game-4inc#14]
Dopo aver testato il gioco a riga di comando, ditemi quali sono le vostre sensazioni in termini di bilanciamento delle meccaniche.
Io personalmente ho rilevato che l'attacco caricato al doppio del danno è eccessivo, andrebbe ridimensionato magari al 50% in più.

**Comment by Fs00** [comment]
Importante: non utilizzate la build presente in Releases per il testing, dato che con il commit 971014d ho risolto un bug che non faceva finire la partita nei turni dispari (primo, terzo, quinto ecc.).

**Comment by alegotta** [comment]
Effettivamente anche a me il doppio pare troppo, il 50% mi sembra più ragionevole.

Dopo un breve test, queste sono alcune cose che ho notato:
- Nella scelta del personaggio:
   - forse sarebbe meglio specificare che le statistiche hanno una leggera randomizzazione e dopo la scelta stampare le statistiche assegnate (comprensive di difesa/attacco);
   - ho visto che qui per ora manca la descrizione:
https://github.com/Fs00/rpg-game-4inc/blob/ad7422709266d2bd5d578de201d9dcfba8889ec1/src/App.java#L44
Sarebbe bello aggiungerla per ogni personaggio, magari usando quelle che hai messo nella Wiki. 
- Per indicare che giocatore deve giocare, sarebbe meglio mettere il nome (Es: TURNO DEL GIOCATORE PIPPO) anziché il numero del giocatore, come è adesso (Es: TURNO DEL GIOCATORE 1)
- Dopo il commit ad7422709266d2bd5d578de201d9dcfba8889ec1, il messaggio "Fuga riuscita/fallita" viene stampato due volte, dalla classe GestionePartita e da quella Personaggio. Decidiamo quale sia meglio tenere!

**Comment by Fs00** [comment]
Ti rispondo per punti, @alegotta:
- Scelta del personaggio:
  - È vero, il fatto della randomizzazione non l'ho messo perché ero preoccupato di far funzionare il gioco in sé, provvedo quanto prima a creare un metodo in Personaggio che stampi tutte le statistiche.
  - Pensavo per quella di creare un attributo `descrizione` in Personaggio, ditemi voi se vi va bene.
- Ottima proposta, provvedo subito.
- Ho notato anch'io, @AlibabaSakura non si era accorto che quei messaggi li avevo già messi in Personaggio. Io terrei quelli di GestionePartita, dato che forse è meglio limitare la stampa di messaggi dalle classi dei personaggi (anche se talvolta è necessario, vedi ad es. il contrattacco.)

Allora porto l'attacco caricato da danno doppio ad aumentato del 50%. D'accordo, @AlibabaSakura?

**Comment by alegotta** [comment]
Ok per tutto!

**Comment by Fs00** [comment]
Ho implementato le tue proposte @alegotta, eccetto per la descrizione (che probabilmente farò domani). Ho anche inserito un controllo per evitare che i due giocatori scelgano lo stesso nome.

**Comment by Fs00** [comment]
Comunque, riguardo il bilanciamento, ho notato altri due problemi:
- La probabilità di contrattacco mi sembra un po' bassina, non capita veramente quasi mai. Solo che aumentando il divisore della velocità avvantaggeremmo troppo il Contadino (con un divisore di 1,3 arriverebbe al 38% dal 33% attuale), mentre il Soldato ne avrebbe un minimo beneficio (da 13% a 15% con un divisore di 1,3). Se vogliamo ritoccare questo aspetto, bisognerebbe cambiare totalmente la formula della probabilità.
- Il Soldato ha la possibilità di attivare la difesa senza perdere l'attacco caricato. Esempio:
  - turno 1: il Soldato carica l'attacco
  - turno 2: il Soldato prepara la difesa
  - turno 3: il Soldato subisce danni dimezzati e inoltre **può ancora sfruttare il bonus dell'attacco (NON VA BENE!)**
Dovremmo sistemarlo appena possibile (fai tu, @alegotta?)

**Comment by Fs00** [comment]
Ripensandoci, forse la probabilità di contrattacco non è il problema.
Credo che **l'attacco di tutti i personaggi in generale sia troppo alto.** Ho fatto altri test ed effettivamente le partite durano veramente poco, qualcosa come 4/5 turni a personaggio. Questo non solo rende completamente inutile la feature della stamina, ma rende gli attacchi caricati (e anche i contrattacchi) veramente devastanti in caso di differenze di stats molto accentuate (vedi ad esempio un Contadino vs Mercenario).
Perciò ho pensato che si potrebbe **ridurre di un 10-15 punti l'attacco** di tutti i personaggi, accompagnato magari da una **riduzione della difesa di 5 punti** per evitare poi che il Contadino non riesca a torcere un capello nemmeno al Mercenario.
Se applichiamo questa modifica, poi, per queste due statistiche sarebbe meglio ridurre il range di randomizzazione da 5 a 4 per bilanciare meglio le cose.
Fate qualche test e ditemi cosa ne pensate.

**Comment by alegotta** [comment]
Io sono d'accordo con la diminuzione.

**Comment by Fs00** [comment]
Dato che la proposta sopra è stata accolta (con riduzione dell'ATK a 10), l'ho implementata con il commit fd03d85.
Solo che mi ero dimenticato di aggiornare le informazioni nel main, quindi ho sistemato la cosa con il commit e846a2e (e le ho spostate nei metodi statici `getDescrizione()`, così evitiamo altre sviste del genere in futuro).
_(eh sì, mi dispiace @alegotta, ma ci sarà da fare una rc2 :/)_

**Comment by alegotta** [comment]
Eh beh :)
Mi sembra che così la situazione sia più equilibrata. Direi che si può chiudere l'issue.
