### ISSUE TITLE
Localizzazione stringhe

### ISSUE THREAD

**Issue by AlibabaSakura** [Fs00/rpg-game-4inc#15]
Stavo pensando che magari per stringhe all'interno di "GestionePartita" (O altre stringhe in classi non main) si potesse fare una classe di gestione delle lingue utilizzando dei file JSON come "contenitori" di stringhe (l'idea poteva anche essere usare i database ma già così il codice potrebbe diventare un po' complesso rispetto al JSON).

Ho già adocchiato questa libreria open source: https://code.google.com/archive/p/json-simple/ e una piccola guida su come usarla c'è qua: https://www.tutorialspoint.com/json/json_java_example.htm

**Comment by Fs00** [comment]
L'idea in sé non è brutta (anche se ai JSON preferirei un DB, dato che almeno non deve parsare un file di testo), ma probabilmente per implementare la localizzazione ci sono già dei metodi più "comodi" che ci risparmierebbero un bel po' di lavoro.
Allo stato attuale delle cose, però, mi sembra un qualcosa di veramente superfluo che ci farebbe solo perdere tempo. Questa cosa la lascio cercare a te, solo *dopo che saremo a buon punto con la GUI* però.

**Comment by alegotta** [comment]
Quoto in toto con @Fs00

**Comment by Fs00** [comment]
Chiudo in quanto il lavoro per il progetto è ormai chiuso. @AlibabaSakura puoi sempre forkare il repository e continuare sul tuo account.
