### ISSUE TITLE
Presentazione e nome del gioco

### ISSUE THREAD

**Issue by alegotta** [Fs00/rpg-game-4inc#16]
Ho iniziato a fare la presentazione del gioco, che vi ho condiviso su Google Drive.

A tal proposito, credo dovremmo decidere un nome da dare al gioco, per distinguerlo da quello degli altri gruppi.

_P.S.: Ovviamente la presentazione è in stato embrionale (WIP), ma ogni suggerimento già da ora è ben accetto._

**Comment by Fs00** [comment]
Il nome? Ardua domanda, ci penserò questo pomeriggio e se ho qualche idea la metterò qui.
Comunque la presentazione, se hai letto la scaletta della prof, deve iniziare con la presentazione del team e in cosa ciascuno dei componenti è specializzato (ricordo il nome del team, _TripleBrackets_).
Per la parte sul "perché la vostra soluzione è il gioco migliore", io già un paio di idee:
- Ogni partita è diversa dall'altra (randomizzazione delle stats)
- Il contrattacco fornisce la possibilità di cambiare le sorti di una partita in bilico

Sulla parte del "business model", direi che il target è quello dei giovani. Per il resto veramente non saprei :D

**Comment by Fs00** [comment]
Mi è venuto in mente un possibile nome per il gioco: _Swords&Pitchforks_, tradotto letteralmente "Spade e Forconi", a sottolineare la presenza anche di combattenti non convenzionali.
Cosa ne pensate?

**Comment by AlibabaSakura** [comment]
「とうけん・と・ピッチフォーク」… (non farci caso, è una specie di porting del nome che hai messo). La tua idea ci sta, dai. Penso ci possa essere un titolo migliore la possiamo tenere come buona.

**Comment by Fs00** [comment]
Sono andato un po' avanti con la presentazione. Per la parte del team, che ne direste ognuno di mettere la rapida descrizione di uno degli altri membri come ho già fatto con @AlibabaSakura (non più lunga di 2 righe e mezzo)? Ad esempio @alegotta potrebbe scrivere la mia e @AlibabaSakura quella di @alegotta.
Ovviamente se qualcuno non è d'accordo con quanto scritto dall'altro, può sempre modificarlo.

**Comment by Fs00** [comment]
Vi ricordo che c'è anche un motto da scegliere per il gruppo. Voi cosa proponete?

**Comment by Fs00** [comment]
Per il motto, mi sono venute due idee:
_"Designing software to make you smile"_
_"Designing software for fun"_
Mi sembrano tutte e due valide, anche se la prima mi sembra più originale e meno anonima.

Comunque, dobbiamo decidere anche chi presenta cosa. Pensavo di fare:
- @alegotta slide 1-3 fino alle statistiche (visto che comunque bisogna spiegarle)
- @AlibabaSakura slide 3 dalle statistiche-4
- @Fs00 dalla 5 in poi (dato che sono quelle più lagnose e in cui finora ci ho messo idee solo io)

Ditemi che motto scegliete e se vi va bene questa scaletta.

**Comment by alegotta** [comment]
Per lo slogan penso che il primo possa andare bene. Ho provato a pensare anch'io ad un motto, ma non mi è venuto in mente niente di soddisfacente :/. 
OK per la scaletta.

**Comment by AlibabaSakura** [comment]
Io ci ho provato per il motto ma nulla di buono mi è venuto in mente. Mi va bene la seconda ma anche la prima non sembra male.
Inoltre, per la presentazione avrei una screenshot buona per la versione in alpha della GUI.
