### ISSUE TITLE
Scelta del package name

### ISSUE THREAD

**Issue by alegotta** [Fs00/rpg-game-4inc#2]
Il package name è "ittbuonarroti.rpggame" o "com.ittbuonarroti.rpggame"?
Prima del commit 826b3e36d1afddc7d44ecf34e6733093ca073975 veniva usato "com.ittbuonarroti.rpggame", mentre dopo "ittbuonarroti.rpggame".
Decidiamo quale tenere!

**Comment by Fs00** [comment]
Io ho cambiato al secondo perché il "com" non aveva molto senso per noi
(non siamo un'azienda) e anche perché così c'era un sottolivello di
cartelle in meno (anche se adesso non serve più dato che abbiamo risolto il
problema). Onestamente preferirei il secondo ma comunque non mi cambia
granché.

**Comment by alegotta** [comment]
Perfetto, allora teniamo "ittbuonarroti.rpggame".
