### ISSUE TITLE
Struttura ereditarietà classi: come facciamo?

### ISSUE THREAD

**Issue by Fs00** [Fs00/rpg-game-4inc#3]
Prima domanda: Mercenario non è una derivata di soldato? Praticamente ha molti dei metodi che ha anche soldato, però è anche vero che dovremmo in qualche modo differenziarlo da esso...

Seconda domanda: Ma il Debole? A quanto ho capito "le prende" soltanto e non ha molto senso in un gioco a turni come il nostro. E se facessimo il Contadino come derivato di Debole, inteso come "colui che non fa il combattimento di mestiere"? In tal caso, però dovremmo decidere quali metodi accomunano i "deboli"...

**Comment by alegotta** [comment]
Allora, i personaggi da fare sono _per forza_ 4: Debole e Contadino (Buoni); Mercenario e Soldato (Cattivi).

- Il **Debole** ha solo i metodi della classe Personaggio _(A cui mancano ancora diversi metodi, vedi #5)_
- Il **Contadino** idem ma può difendersi (cioè in caso di attacco può controattaccare, ma non può attaccare per primo)
- Il **Mercenario** ed il **Soldato** possono sia attaccare che difendersi. Sulla differenza tra i due sono in dubbio anche io... Dovremo chiedere il codice del gruppo del Mercenario per capire bene. Di sicuro non erano state previste come derivate l'una dall'altra. 

Per racchiudere le similitudini si potrebbe pensare di creare le classi astratte Buono/Cattivo per rendere il codice più pulito.

**Comment by alegotta** [comment]
Abbiamo deciso che:
**Mercenario** e **Soldato** derivano da **Combattente**. Si differenziano solo nelle statistiche.
**Debole** e **Contadino** derivano da **Personaggio** (lasciamo così com'è)
