### ISSUE TITLE
Statistiche e loro randomizzazione

### ISSUE THREAD

**Issue by Fs00** [Fs00/rpg-game-4inc#4]
@AlibabaSakura suggeriva di randomizzare leggermente i valori delle statistiche nella creazione del personaggio. Se decidiamo di farlo, dobbiamo definire i dettagli implementativi e i range in %.

**Comment by AlibabaSakura** [comment]
Ho già dato un piccolo spunto per i valori standard. Basterebbe alla fine usare un rand() tra 0 e 4 per ogni valore e poi un altro rand() per decidere se aggiungere o togliere questi valori.
Esempio di valori (notare che i parametri non coincidono con quelli della classe Personaggio per motivi dimostrativi)

```java
/**
 * Statistiche base per l'RNG interno. Le statistiche varieranno di circa +/- 4 (aggiunta o riduzione)
 *
 * Structure:
 * 0 -> HP
 * 1 -> SP
 * 2 -> Attack
 * 3 -> Defense
 * 4 -> Speed
 */
public final String[] weak = {"20", "5", "0", "0", "5"};
public final String[] soldier = {"40", "15", "15", "15", "10"};
public final String[] farmer = {"25", "10", "7", "7", "7"};
public final String[] mercenary = {"50", "20", "20", "10", "15"};
```

**Comment by alegotta** [comment]
Abbiamo deciso queste statistiche:
_Personaggio = [ PV, ATK, DEF, VEL, Stamina ]_
Debole = [ 50, 0, 0, 40, 5 ]
Contadino = [ 100, 35, 10, 50, 15 ]
Soldato = [ 180, 55, 35, 20, 25 ] 
Mercenario = [ 200, 60, 25, 30, 22 ]

Difesa: intero da sottrarre al danno. Se il danno è minore di 1, va portato ad 1
Stamina: turni che il personaggio può combattere
Attacco: danno (punti vita che si perdono) non mitigato dalla difesa

Randomizzazione: +/- 2 per la stamina; +/- 5 per tutte le altre
