### ISSUE TITLE
Convenzioni di scrittura del codice

### ISSUE THREAD

**Issue by Fs00** [Fs00/rpg-game-4inc#6]
Se per voi non è un problema, riguardo alle graffe suggerisco di formattare il codice in maniera uniforme per tutti come sotto:
```
function a()
{
}
```
@AlibabaSakura so che a te non va a genio. Se proprio non riesci a fare a meno delle graffe sulla stessa riga, lasciamo perdere e ognuno fa come gli sta comodo (anche se comunque uniformare tutto sarebbe meglio, se possibile).

**Comment by alegotta** [comment]
Per me è abbastanza indifferente, va bene quello che hai proposto.

Se scegliamo questa convenzione, bisognerà modificare le impostazioni di IntelliJ di modo che non cambi la formattazione in automatico.
Questi sono i passaggi: Impostazioni - Code Style - Java - Wrapping and Braces - Braces Placement - selezionare Next Line
![Foto di chiarimento](https://i.imgur.com/H1snPk4.png)

**Comment by alegotta** [comment]
Proporrei di aggiungere alle guidelines il fatto di limitare l'uso del 'this' solo quando strettamente necessario (es: variabili chiamate con lo stesso nome).
In che lingua scriviamo i commit? Nonostante io e @Fs00 abbiamo iniziato a farli in inglese, forse sarebbe meglio uniformare tutto e scrivere in italiano pure quelli. Idem per i file .md...

**Comment by Fs00** [comment]
Sul limitare l'uso del this quoto, provvedo subito.
Gli .md li terrei in inglese, visto che comunque la piattaforma è di dominio pubblico (e quindi internazionale) e stessa cosa per i commit. In italiano bastano gli issue, dato che discutiamo fra di noi. La vera domanda è in che lingua fare la wiki (#8), visto che poi dovrà leggerla l'insegnante...

**Comment by Fs00** [comment]
@AlibabaSakura Riguardo al primo post, cosa ne pensa?

**Comment by Fs00** [comment]
Per non penalizzare troppo @AlibabaSakura, le graffe rimarranno sulla stessa riga. Tuttavia, i blocchi else e catch andranno a caporiga per non "ammucchiare" troppo il codice.
Ho aggiunto al file CONTRIBUTING.md il contenuto del file da copiare nella cartella .idea del progetto per impostare lo stile del codice. **Importante: quando committerete, dovrete selezionare la spunta "Reformat code".**
