### ISSUE TITLE
Gestione della documentazione 

### ISSUE THREAD

**Issue by alegotta** [Fs00/rpg-game-4inc#8]
Proporrei di generare la documentazione che scriviamo con JavaDoc nella cartella /docs _(da creare)_
Poi @Fs00 dovrebbe abilitare [Github Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) in modo che possa essere visibile da chiunque.

Oltre al JavaDoc, a gioco finito si può pensare di aggiungere una piccola spiegazione del funzionamento del gioco ed alcuni screenshot nel ReadMe.

**Comment by Fs00** [comment]
Sulla cartella /docs quoto in toto, invece che GitHub Pages la mia intenzione era quella di fare una wiki, molto più facile e veloce da gestire.
In caso gli screenshots li mettiamo là, invece che nel Readme (che è più ad un livello sviluppatore).

**Comment by alegotta** [comment]
Ok per la Wiki. 
Mi sono spiegato male, GitHub Pages servirebbe solo per visualizzare il JavaDoc renderizzato dal browser (altrimenti si vede solo il codice html in plain text, che non è il massimo).

**Comment by Fs00** [comment]
Ah ok, buona idea, ci penseremo.

**Comment by Fs00** [comment]
Riapro per assegnare ad @alegotta la creazione della pagina GitHub Pages e della cartella docs per il Javadoc.
Da richiudere quando il lavoro in questo senso sarà completato.

**Comment by alegotta** [comment]
Io non posso gestire Github Pages, questa funzione è esclusiva del proprietario del repo (@Fs00). Ok per il resto.

**Comment by Fs00** [comment]
Ho creato il sito GitHub Pages ([fs00.github.io/rpg-game-4inc](https://fs00.github.io/rpg-game-4inc/)) con il Javadoc e le pagine mancanti nella wiki.
Chiudo l'issue, dato che il grosso è stato fatto. In caso di informazioni da aggiornare/completare, ne parleremo quando ci si vede.

**Comment by Fs00** [comment]
@alegotta Sarebbe buono se integrassi la Javadoc con le descrizioni relative ai package, come in questo link: [https://stackoverflow.com/questions/624422/how-do-i-document-packages-in-java](https://stackoverflow.com/questions/624422/how-do-i-document-packages-in-java).
Inoltre, quando puoi, revisiona/integra le documentazioni delle classi in modo da evitare di lasciare "buchi".

**Comment by Fs00** [comment]
Ottimo, chiudo.
