### ISSUE TITLE
Inconguenze nella classe Personaggio

### ISSUE THREAD

**Issue by Fs00** [Fs00/rpg-game-4inc#9]
1. Perché abbiamo i setter e i getter se i campi sono protected? I campi dovrebbero essere private, a mio avviso
2. modificaHP() deve essere un override di subisciColpo(), altrimenti a cosa serve questo metodo nella classe base?
3. setPuntiStamina() avrebbe più senso come decrementaStamina(), un metodo che dovrebbe essere chiamato dalla classe di gestione a ogni turno

**Comment by Fs00** [comment]
Punti 1 e 2 sistemati con la commit [603472e](https://github.com/Fs00/rpg-game-4inc/commit/603472e7550099dab210eb0ee7cc6ac7fd416c94), ditemi cosa ne pensate riguardo al punto 3.

**Comment by alegotta** [comment]
Ma sbaglio o la stamina può anche essere recuperata?
In tal caso forse si potrebbero predisporre due metodi:
- **decrementaStamina()** chiamato ad ogni turno, il quale diminuisce di uno l'attributo puntiStamina
- **ripristinaStamina()** chiamato a fine scontro, il quale riporta la stamina al valore puntiStaminaTotali

**Comment by Fs00** [comment]
Sulla questione del recupero della stamina non abbiamo mai detto nulla. In caso dovremmo decidere se implementarlo o meno.
Comunque, a cosa dovrebbe servire _ripristinaStamina()_ se poi tanto la classe di gestione si riazzera alla fine di ogni partita?

**Comment by Fs00** [comment]
_decrementaStamina()_ è stato aggiunto con la commit 826ba7a, dato che mi serviva per poter gestire la partita. Chiudo dato che per questa discussione non c'è altro da dire.
